name: automerge
on:
  issue_comment:
    types: [created]
jobs:
  automerge:
    if: ${{ github.event.issue.pull_request && github.event.comment.author_association == 'OWNER' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check author_association
        run: |
          echo author_association is ${{ github.event.comment.author_association }}
          echo Hello, this workflow is allowed to OWNERS.
          
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/approve') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            approved
            
      - name: automerge-lgtm-approved
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "approved,lgtm,!wip"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: "merged"
          UPDATE_METHOD: "rebase"
